//! # tauri-plugin-axum
//! 
//! ```sh
//! cargo add tauri-plugin-axum
//! ```
//! 
//! ```sh
//! pnpm i @mcitem/tauri-plugin-axum
//! ```
//! 
//! - [Permissions](https://github.com/mcitem/tauri-plugin-axum/blob/master/tauri-plugin-axum/permissions/autogenerated/reference.md)
//! 
//! # Example
//! 
//! ```rs
//! #[derive(Serialize, Deserialize)]
//! struct Greet {
//!     axum: String,
//!     tauri: String,
//! }
//! 
//! async fn post_handle(Json(j): Json<Greet>) -> Json<Greet> {
//!     Json(Greet {
//!         axum: format!("axum, {}!", j.axum),
//!         tauri: format!("tauri, {}!", j.tauri),
//!     })
//! }
//! 
//! tauri::Builder::default()
//!     .plugin(tauri_plugin_axum::init(
//!         Router::new()
//!             .route("/", routing::get(|| async { "Hello, World!" }))
//!             .route("/post", routing::post(post_handle))
//!     ))
//! ```
//! 
//! ```ts
//! import { axum } from "@mcitem/tauri-plugin-axum";
//! axum.get<string>("/").then((response) => {
//!   console.log(response.body); // "Hello, World!"
//! });
//! axum.post<{ axum: string; tauri: string }>("/post", {
//!   axum: "hello axum",
//!   tauri: "hello tauri",
//! });
//! ```
//! 
//! - [Example](https://github.com/mcitem/tauri-plugin-axum/blob/master/example/tauri-app)
//! 
//!   [main.ts](https://github.com/mcitem/tauri-plugin-axum/blob/master/example/tauri-app/src/main.ts)
//! 
//!   [lib.rs](https://github.com/mcitem/tauri-plugin-axum/blob/master/example/tauri-app/src-tauri/src/lib.rs)
//! 
//! ## Run Example
//! 
//! ```sh
//! git clone https://github.com/mcitem/tauri-plugin-axum
//! cd tauri-plugin-axum
//! pnpm install
//! pnpm build
//! pnpm --filter tauri-app install
//! pnpm --filter tauri-app tauri dev
//! ```

use axum::body::Body;
use axum::extract::Request;
use axum::Router;
use http_body_util::BodyExt;
use std::collections::HashMap;
use tauri::ipc::{InvokeBody, Request as IpcRequest};
use tauri::{
    plugin::{Builder, TauriPlugin},
    Manager, Runtime,
};
use tower::Service;

mod commands;
mod error;
mod models;

pub use error::{Error, Result};
pub use models::*;

/// Extensions to [`tauri::App`], [`tauri::AppHandle`] and [`tauri::Window`] to access the axum APIs.
pub trait AxumExt<R: Runtime> {
    fn axum(&self) -> &Axum;
}

impl<R: Runtime, T: Manager<R>> crate::AxumExt<R> for T {
    fn axum(&self) -> &Axum {
        self.state::<Axum>().inner()
    }
}

pub struct Axum(Router);

impl Axum {
    pub async fn call(&self, req: IpcRequest<'_>) -> Result<AxumResponse> {
        let mut rr = Request::builder();
        let _ = std::mem::replace(rr.headers_mut().unwrap(), req.headers().clone());

        rr = rr.uri(req.headers().get("x-uri").ok_or(Error::Uri)?.as_ref());
        rr = rr.method(req.headers().get("x-method").ok_or(Error::Method)?.as_ref());

        let bytes = match req.body() {
            InvokeBody::Json(v) => serde_json::to_vec(&v)?,
            InvokeBody::Raw(r) => r.to_vec(),
        };

        let result = rr.body(Body::from(bytes))?;
        let response = self.0.clone().call(result).await.unwrap();
        let status = response.status();
        let mut headers: HashMap<String, String> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), String::from(v.to_str().unwrap_or_default())))
            .collect();
        let colleted = response.into_body().collect().await?;

        if let Some(t) = colleted.trailers() {
            for (k, v) in t.iter() {
                headers.insert(k.to_string(), String::from(v.to_str().unwrap_or_default()));
            }
        }

        Ok(AxumResponse {
            status,
            headers,
            body: colleted.to_bytes(),
        })
    }
}

/// Initializes the plugin.
/// ```rust
/// tauri::Builder::default()
///     .plugin(tauri_plugin_axum::init(
///         Router::new()
///             .route("/", routing::get(|| async { "Hello, World!" }))
///             .route("/post", routing::post(post_handle))
///     ))
/// ```
pub fn init<R: Runtime>(router: Router) -> TauriPlugin<R> {
    Builder::new("axum")
        .invoke_handler(tauri::generate_handler![commands::call])
        .setup(|app, __api| {
            app.manage(Axum(router));
            Ok(())
        })
        .build()
}
