[default]
description = "Default permissions for axum plugin"
permissions = [
    "allow-call",
    "allow-call-json",
    "allow-fetch",
    "allow-fetch-send",
    "allow-fetch-cancel",
    "allow-fetch-read-body",
]
